# app/config/config.yml
knpu_oauth2_client:
  # can be set to the service id of a service that implements Guzzle\ClientInterface
  # http_client: null

  # options to configure the default http client
  # http_client_options
  #     timeout: 0
  #     proxy: null
  #     Use only with proxy option set
  #     verify: false

  clients:
    # will create service: "knpu.oauth2.client.github"
    # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\GithubClient
    # composer require league/oauth2-github
    github:
      # must be "github" - it activates that type!
      type: github
      # add and configure client_id and client_secret in parameters.yml
      client_id: '%env(OAUTH_GITHUB_CLIENT_ID)%'
      client_secret: '%env(OAUTH_GITHUB_CLIENT_SECRET)%'
      # a route name you'll create
      redirect_route: github_connect_check
      redirect_params: {}

      # whether to check OAuth2 "state": defaults to true
      # use_state: true