home:
  path: /
  controller: App\Controller\Main\MainController::homeAction

logout:
  path: /logout
  controller: App\Controller\Main\MainController::logoutAction

github_connect:
  path: /github/connect
  controller: App\Controller\Github\GithubController::connectAction

github_connect_check:
  path: /github/connect/check
  controller: App\Controller\Github\GithubController::connectCheckAction

github_repos:
  path: /github/repos
  controller: App\Controller\Github\GithubController::reposAction

github_profile:
  path: /github/profile
  controller: App\Controller\Github\GithubController::profileAction